Add GitHub Actions step to check the deployment (#31)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,3 +24,13 @@ jobs:
         run: flyctl deploy --remote-only
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
+      - name: Check deploy
+        run: |
+          response=$(curl -s -o /dev/null -m 60 -w "%{http_code}" https://rss-feed.fly.dev/actuator/health)
+          if [ $response -eq 200 ]; then
+            echo "Application is healthy"
+          else
+            echo "Deploy failed"
+            exit 1
+          fi
+
